### ISSUE TITLE
Mode 00

### ISSUE THREAD

**Issue by dfujim** [dfujim/bdata#7]
@rmlmcfadden: What is up with mode 00? For example 40236 from 2003. There are also 20 runs in 2003 which seem more "normal", but this run has no dwell times logged. Rather there is  "ticks" histogram which doesn't seem to be the time axis. 

Drawing the asymmetry (calculating by hand), I get something that looks like an SLR recovery to equilibrium, but it's just the beam off portion or something:

```python
import bdata as bd
import matplotlib.pyplot as plt

d = bd.bdata(40236, 2003)   
plt.plot( (d.Bp - d.Fp) / (d.Bp + d.Fp) )  
plt.plot( (d.Bn - d.Fn) / (d.Bn + d.Fn) )  
```

**Comment by rmlmcfadden** [comment]
Beats me - I think we'd need to consult someone who was around back then for a definitive answer.

My guess is they are mode `20` runs and the string in the `.msr` header is really a typo that propagated over from the DAQ (wouldn't be the first time). While this explanation is a bit naive, the data are qualitatively consistent with it. Moreover, there is no mention of any type `0` runs in the [β-NMR documentation] (only type `1` and `2`) and only one run mode that includes a `0` (i.e., `20`).

Hmm - even without consulting the old logbooks, I was able to infer the prebeam/beamon/beamoff dwelltimes, which can be applied manually so that the run can be processed in the usual way. Complete example below:

```python
import bdata as bd
from mudpy.containers import mdict
from bfit.fitting.functions import  pulsed_strexp
from scipy.optimize import curve_fit
import numpy as np
import matplotlib.pyplot as plt

# read the .msr file
data = bd.bdata(40237, year=2003)

# manually define/apply some PPG parameters needed for processing
custom_ppg_parameters = mdict(
    {
        "dwelltime": mdict({"mean": 10}),
        "prebeam": mdict({"mean": 50}),
        "beam_on": mdict({"mean": 50}),
    }
)
data.ppg = custom_ppg_parameters

# calculate the combined asymmetry
time, asymmetry, asymmetry_error = data.asym("c", rebin=1, deadtime=0)

# define the stretched exponential relaxation function
fcn = pulsed_strexp(bd.life["Li8"], data.get_pulse_s())

# fit the data (omitting the bins where the uncertainty is zero)
popt, pcov = curve_fit(
    fcn,
    time[asymmetry_error != 0],
    asymmetry[asymmetry_error != 0],
    sigma=asymmetry_error[asymmetry_error != 0],
    p0=[1.0, 0.75, 0.15],
)

# make the figure/axis and plot the data
fig, ax = plt.subplots(1, 1, constrained_layout=True)

ax.errorbar(time, asymmetry, yerr=asymmetry_error, fmt="o", zorder=1)

t = np.linspace(np.min(time), np.max(time), 500)
ax.plot(t, fcn(t, *popt), "-", zorder=2)

ax.set_xlabel("Time (s)")
ax.set_ylabel("Asymmetry")

plt.show(block=True)
```

In some sense, this is an edge case in the data - there aren't that many runs of this type, they are all <i>very</i> old, and manual input is required to analyze them.

If you're wondering about how [bfit] should deal with these runs, I think ignoring them (which it already does) is reasonable. Maybe a warning should be emitted when these runs are accessed?

[β-NMR documentation]: https://dasdevpc2.triumf.ca/online/bnmr/index.html
[bfit]: https://github.com/dfujim/bfit

**Comment by dfujim** [comment]
Yeah I figured some kind of manual setting would be needed, good job on figuring out the parameters though! I'm actually amused that your example worked since `mhist` was never intended to store data directly. In theory, the intended variables will execute faster but in practice I don't think it makes much of a difference. 

I [updated mudpy](https://github.com/dfujim/mudpy/commit/8cb167f2f4ab0ccc6a913d799012e83cd016373c) such that the containers now have `__init__` functions, which will help people create their own variables. 

A drawing MWE: 

```python
from mudpy.containers import mvar
import bdata as bd
import matplotlib.pyplot as plt

plt.ion()
dat = bd.bdata(40237, 2003)
dat.ppg['dwelltime'] = mvar(mean=10)
dat.ppg['prebeam'] = mvar(mean=50)
plt.errorbar(*dat.asym('c'))
```

I'm toying with the idea of including some new classes to reduce the mudpy-related knowledge needed to add variables properly. Something like: 

```python
from mudpy.containers import mdict, mvar

class vdict(mdict):
    def set(self, key, **kwargs):
        self[key] = mvar(**kwargs)
```

so that these lines in the MWE become slightly more elegant:

```python
dat.ppg.set('dwelltime', mean=10)
dat.ppg.set('prebeam', mean=10)
```

This may actually help solve a [bfit issue](https://github.com/dfujim/bfit/issues/70) raised by @vkarner.

**Comment by rmlmcfadden** [comment]
Confirmed - mode `00` is the just the historic name for SLR runs. At some point it was changed to `20` - probably to harmonize the naming patterns for time-differential and time-integral modes.
